# Generated by Django 5.1 on 2024-09-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_inbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxmessage',
            old_name='conversatino',
            new_name='Conversation',
        ),
    ]
